// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWOdDixP2gjpALPAJi3qOwuoZiHXM7HNA',
    appId: '1:1056945213516:web:f31c7e59b6eb2ec5dea4e9',
    messagingSenderId: '1056945213516',
    projectId: 'gabonmeuble-b8ebc',
    authDomain: 'gabonmeuble-b8ebc.firebaseapp.com',
    storageBucket: 'gabonmeuble-b8ebc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbcXBdBqRn3hv1LNpsjfJzoEtILCcFhD0',
    appId: '1:1056945213516:android:eb1017d0a2694985dea4e9',
    messagingSenderId: '1056945213516',
    projectId: 'gabonmeuble-b8ebc',
    storageBucket: 'gabonmeuble-b8ebc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuJSKYF69rBowmyA1RsoZ2QSnTUu2DDkc',
    appId: '1:1056945213516:ios:ae96c259a01b1f43dea4e9',
    messagingSenderId: '1056945213516',
    projectId: 'gabonmeuble-b8ebc',
    storageBucket: 'gabonmeuble-b8ebc.firebasestorage.app',
    iosBundleId: 'com.example.gabonMeubleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuJSKYF69rBowmyA1RsoZ2QSnTUu2DDkc',
    appId: '1:1056945213516:ios:ae96c259a01b1f43dea4e9',
    messagingSenderId: '1056945213516',
    projectId: 'gabonmeuble-b8ebc',
    storageBucket: 'gabonmeuble-b8ebc.firebasestorage.app',
    iosBundleId: 'com.example.gabonMeubleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWOdDixP2gjpALPAJi3qOwuoZiHXM7HNA',
    appId: '1:1056945213516:web:55c332b510211b16dea4e9',
    messagingSenderId: '1056945213516',
    projectId: 'gabonmeuble-b8ebc',
    authDomain: 'gabonmeuble-b8ebc.firebaseapp.com',
    storageBucket: 'gabonmeuble-b8ebc.firebasestorage.app',
  );
}
